// ---------------------------------------------------------------------------
// mockData.ts — Demo seed data for booking-onwards workflow
//
// These records are merged into App state at startup so every workflow step
// from CS Booking through Admin House BL / BL Approval has items to work
// with, without requiring backend data.
// ---------------------------------------------------------------------------
import type { Inquiry, Booking, ActivityEntry, ContainerLine, ReleaseOrderFields } from './types'

const ts = (daysAgo: number): string =>
  new Date(Date.now() - daysAgo * 86_400_000).toISOString()

const future = (daysFromNow: number): string =>
  new Date(Date.now() + daysFromNow * 86_400_000).toISOString().slice(0, 10)

const mkContainer = (
  containerType: ContainerLine['containerType'],
  quantity: number,
  commodityType: ContainerLine['commodityType'],
  commodityName: string,
  destination: string,
): ContainerLine => ({
  containerType,
  quantity,
  weight: '',
  commodityType,
  commodityName,
  destination,
  isFcl: true,
  zipCode: '',
  doorAgents: [],
  freeTime: '',
})

// ---------------------------------------------------------------------------
// Inquiries at booking-request stage
// → Appear in CS / Sales "Booking" step as "Create Booking" items
// ---------------------------------------------------------------------------
export const MOCK_INQUIRIES: Inquiry[] = [
  // ---------------------------------------------------------------------------
  // Completed inquiries — linked to mock bookings in the Draft BL / Pre-Advice
  // steps. status:'completed' means they are invisible in the workspace pending
  // list but can be looked up for prefilling the booking form.
  // ---------------------------------------------------------------------------
  {
    id: 'INQ-MOCK-C01',
    customer_name: 'Aitken Spence Shipping',       // → BKG-MOCK-008 (Draft BL)
    request: 'FCL Export',
    inquiry_text: 'FCL Export — Colombo → Singapore',
    origin: 'Colombo',
    destination: 'Singapore',
    delivery_type: 'port-to-port',
    sbu: 'Ocean Exports',
    employee_id: 7,
    status: 'completed',
    created_at: ts(28),
    container_type: '20 GP',
    container_qty: 2,
    cargo_weight: 18500,
    incoterm: 'FOB',
    remark: 'Handle with care — fragile glassware. Marks: ASS/SIN/2024',
    containers: [
      mkContainer('20 GP', 2, 'Glass, glassware, ceramic products', 'Industrial Glassware & Components', 'Singapore'),
    ],
    recorded_by: 7,
  },
  {
    id: 'INQ-MOCK-C02',
    customer_name: 'CL Synergy Limited',           // → BKG-MOCK-013 (Pre-Advice)
    request: 'FCL Import',
    inquiry_text: 'FCL Import — Montreal → Colombo',
    origin: 'Montreal',
    destination: 'Colombo',
    delivery_type: 'door-to-door',
    sbu: 'Ocean Imports',
    employee_id: 7,
    status: 'completed',
    created_at: ts(30),
    container_type: '40 HC',
    container_qty: 1,
    cargo_weight: 5252,
    incoterm: 'CIF',
    remark: 'GOLS Certified organic latex. Must maintain ambient temperature. ACI HBL: CLSMTR14146',
    containers: [
      mkContainer('40 HC', 1, 'Rubber and articles thereof', 'GOLS Certified Organic Latex Foam Sheets & Pillows', 'Colombo'),
    ],
    recorded_by: 7,
  },
  {
    id: 'INQ-MOCK-C03',
    customer_name: 'Delmege Forsyth & Co.',        // → BKG-MOCK-014 (Pre-Advice)
    request: 'FCL Export',
    inquiry_text: 'FCL Export — Colombo → Toronto',
    origin: 'Colombo',
    destination: 'Toronto',
    delivery_type: 'port-to-door',
    sbu: 'Ocean Exports',
    employee_id: 8,
    status: 'completed',
    created_at: ts(26),
    container_type: '20 GP',
    container_qty: 2,
    cargo_weight: 11200,
    incoterm: 'FOB',
    remark: 'Ceylon tea — temperature sensitive. Store above 15°C. Marks: DEL/TOR/TEA/2024',
    containers: [
      mkContainer('20 GP', 2, 'Prepared foodstuffs; beverages, spirits, tobacco', 'Ceylon Tea (Orthodox & CTC)', 'Toronto'),
    ],
    recorded_by: 8,
  },
  // ---------------------------------------------------------------------------
  // Active inquiries at booking-request stage
  // ---------------------------------------------------------------------------
  {
    id: 'INQ-MOCK-001',
    customer_name: 'Maliban Biscuits',
    request: 'FCL Export',
    inquiry_text: 'FCL Export — Colombo → Rotterdam',
    origin: 'Colombo',
    destination: 'Rotterdam',
    delivery_type: 'port-to-port',
    sbu: 'Ocean Exports',
    employee_id: 7,
    status: 'pending',
    created_at: ts(4),
    workflow_stage: 'booking-request',
    container_type: '40 HC',
    container_qty: 2,
    containers: [
      mkContainer('40 HC', 2, 'Prepared foodstuffs; beverages, spirits, tobacco', 'Biscuits & Confectionery', 'Rotterdam'),
    ],
    recorded_by: 7,
  },
  {
    id: 'INQ-MOCK-002',
    customer_name: 'Brandix Apparel',
    request: 'FCL Export',
    inquiry_text: 'FCL Export — Colombo → Hamburg',
    origin: 'Colombo',
    destination: 'Hamburg',
    delivery_type: 'port-to-port',
    sbu: 'Ocean Exports',
    employee_id: 8,
    status: 'pending',
    created_at: ts(2),
    workflow_stage: 'booking-request',
    container_type: '20 GP',
    container_qty: 3,
    containers: [
      mkContainer('20 GP', 3, 'Textiles and textile articles', 'Ready-made Garments', 'Hamburg'),
    ],
    recorded_by: 8,
  },
]

// ---------------------------------------------------------------------------
// Bookings — one per downstream workflow step
// ---------------------------------------------------------------------------
export const MOCK_BOOKINGS: Booking[] = [

  // ── Procurement › Booking Request (review-booking-request) ─────────────
  {
    id: 'BKG-MOCK-001',
    quote_id: 'QT-MOCK-001',
    customer_name: 'Dilmah Tea Export',
    origin: 'Colombo',
    destination: 'Felixstowe',
    shipping_line: 'MSC',
    vessel_name: '',
    voyage_number: '',
    container_type: "40'HC",
    quantity: 2,
    status: 'Pending Liner',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: null,
    released_by: null,
    created_at: ts(3),
    confirmed_at: null,
    released_at: null,
    procurement_notified: false,
    notes: 'Preferred MSC or ONE. OBL required.',
    delivery_type: 'port-to-port',
  },
  {
    id: 'BKG-MOCK-002',
    quote_id: 'QT-MOCK-002',
    customer_name: 'Hemas Consumer Brands',
    origin: 'Colombo',
    destination: 'Rotterdam',
    shipping_line: 'Maersk',
    vessel_name: '',
    voyage_number: '',
    container_type: "20'GP",
    quantity: 1,
    status: 'Pending Liner',
    is_urgent: true,
    booked_by: 8,
    confirmed_by: null,
    released_by: null,
    created_at: ts(1),
    confirmed_at: null,
    released_at: null,
    procurement_notified: false,
    notes: 'Urgent — customer needs ETB confirmed by end of month.',
    delivery_type: 'port-to-port',
  },

  // ── Procurement › Booking (confirm-liner-booking) ───────────────────────
  {
    id: 'BKG-MOCK-003',
    quote_id: 'QT-MOCK-003',
    customer_name: 'Cargills Ceylon',
    origin: 'Colombo',
    destination: 'Antwerp',
    shipping_line: 'CMA CGM',
    vessel_name: 'CMA CGM Trocadero',
    voyage_number: 'RA-24567890',
    container_type: "40'GP",
    quantity: 2,
    status: 'RA Assigned',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: null,
    released_by: null,
    created_at: ts(5),
    confirmed_at: null,
    released_at: null,
    procurement_notified: false,
    notes: 'Contract rate applied. CY/CY delivery.',
    delivery_type: 'port-to-port',
  },

  // ── Admin › Release (release-booking) ──────────────────────────────────
  {
    id: 'BKG-MOCK-004',
    quote_id: 'QT-MOCK-004',
    customer_name: 'Lanka Tiles',
    origin: 'Colombo',
    destination: 'Hamburg',
    shipping_line: 'Hapag-Lloyd',
    vessel_name: 'Hamburg Express',
    voyage_number: '034W',
    container_type: "20'GP",
    quantity: 3,
    status: 'Liner Confirmed',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: null,
    created_at: ts(8),
    confirmed_at: ts(2),
    released_at: null,
    procurement_notified: true,
    notes: 'Hapag-Lloyd confirmed. OBL required.',
    delivery_type: 'port-to-port',
  },

  // ── Admin › Cutoff (record-cutoff) ─────────────────────────────────────
  // Released, no cutoff date → shows only in Cutoff step
  {
    id: 'BKG-MOCK-005',
    quote_id: 'QT-MOCK-005',
    customer_name: 'MAS Holdings',
    origin: 'Colombo',
    destination: 'Rotterdam',
    shipping_line: 'ONE',
    vessel_name: 'ONE Maneuver',
    voyage_number: '0139W',
    container_type: "40'HC",
    quantity: 4,
    status: 'Released',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: 7,
    created_at: ts(14),
    confirmed_at: ts(7),
    released_at: ts(3),
    procurement_notified: true,
    notes: 'Release order sent via email.',
    delivery_type: 'port-to-port',
    // no si_cutoff_date / bl_cutoff_date → will NOT appear in SI Reminder
  },

  // ── Admin › SI Reminder (request-si) ───────────────────────────────────
  // Released, cutoff date set, SI not yet requested
  // Note: mock activity log entry marks cutoff as done → skips Cutoff step
  {
    id: 'BKG-MOCK-006',
    quote_id: 'QT-MOCK-006',
    customer_name: 'Lalan Group',
    origin: 'Colombo',
    destination: 'Le Havre',
    shipping_line: 'CMA CGM',
    vessel_name: 'CMA CGM Trocadero',
    voyage_number: 'FE-234W',
    container_type: "20'GP",
    quantity: 2,
    status: 'Released',
    is_urgent: false,
    booked_by: 8,
    confirmed_by: 5,
    released_by: 8,
    created_at: ts(16),
    confirmed_at: ts(9),
    released_at: ts(5),
    procurement_notified: true,
    notes: '',
    delivery_type: 'port-to-port',
    si_cutoff_date: future(7),
    bl_cutoff_date: future(10),
    si_requested: false,
  },

  // ── Admin › Submit SI (submit-si) ──────────────────────────────────────
  // SI already requested, not yet submitted
  {
    id: 'BKG-MOCK-007',
    quote_id: 'QT-MOCK-007',
    customer_name: 'John Keells Holdings',
    origin: 'Colombo',
    destination: 'Jebel Ali',
    shipping_line: 'Maersk',
    vessel_name: 'Maersk Colombo',
    voyage_number: 'AE-445W',
    container_type: "40'HC",
    quantity: 1,
    status: 'Released',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: 7,
    created_at: ts(18),
    confirmed_at: ts(10),
    released_at: ts(6),
    procurement_notified: true,
    notes: 'Seaway Bill requested.',
    delivery_type: 'port-to-port',
    si_cutoff_date: future(4),
    bl_cutoff_date: future(6),
    si_requested: true,
    si_submitted: false,
  },

  // ── Admin › Draft BL (send-draft-bl) — port-to-port ────────────────────
  // SI submitted, Draft BL not yet sent
  {
    id: 'BKG-MOCK-008',
    quote_id: 'QT-MOCK-008',
    customer_name: 'Aitken Spence Shipping',
    origin: 'Colombo',
    destination: 'Singapore',
    shipping_line: 'COSCO',
    vessel_name: 'COSCO Excellence',
    voyage_number: 'CS-2209E',
    container_type: "20'GP",
    quantity: 2,
    status: 'Released',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: 7,
    created_at: ts(20),
    confirmed_at: ts(12),
    released_at: ts(8),
    procurement_notified: true,
    notes: '',
    delivery_type: 'port-to-port',
    si_requested: true,
    si_submitted: true,
    draft_bl_sent: false,
  },

  // ── Admin › BL Approval (bl-approval) — port-to-port ───────────────────
  // Draft BL sent to customer, awaiting approval response
  {
    id: 'BKG-MOCK-009',
    quote_id: 'QT-MOCK-009',
    customer_name: 'Hirdaramani Apparel',
    origin: 'Colombo',
    destination: 'Rotterdam',
    shipping_line: 'Evergreen',
    vessel_name: 'Ever Given',
    voyage_number: 'EG-0401E',
    container_type: "40'GP",
    quantity: 2,
    status: 'Released',
    is_urgent: false,
    booked_by: 8,
    confirmed_by: 5,
    released_by: 8,
    created_at: ts(22),
    confirmed_at: ts(14),
    released_at: ts(10),
    procurement_notified: true,
    notes: '',
    delivery_type: 'port-to-port',
    si_requested: true,
    si_submitted: true,
    draft_bl_sent: true,
    bl_status: 'pending',
  },

  // ── Admin › Master BL (record-master-bl) — door-to-door ─────────────────
  // SI submitted, Master BL not yet recorded
  {
    id: 'BKG-MOCK-010',
    quote_id: 'QT-MOCK-010',
    customer_name: 'Brandix Logistics',
    origin: 'Colombo',
    destination: 'Hamburg',
    shipping_line: 'MSC',
    vessel_name: 'MSC Flaminia',
    voyage_number: 'FL-339W',
    container_type: "40'HC",
    quantity: 3,
    status: 'Released',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: 7,
    created_at: ts(25),
    confirmed_at: ts(16),
    released_at: ts(12),
    procurement_notified: true,
    notes: 'Door-to-door delivery. Hamburg warehouse.',
    delivery_type: 'door-to-door',
    si_requested: true,
    si_submitted: true,
    master_bl_recorded: false,
  },

  // ── CS › Release Order (release-booking) ────────────────────────────────
  // Liner Confirmed, release order attached by Procurement — ready for CS to release
  {
    id: 'BKG-MOCK-012',
    quote_id: 'QT-MOCK-012',
    customer_name: 'Expo Lanka Holdings',
    origin: 'Colombo',
    destination: 'Felixstowe',
    shipping_line: 'MSC',
    vessel_name: 'MSC America',
    voyage_number: 'QB614W',
    container_type: "20'GP",
    quantity: 3,
    status: 'Liner Confirmed',
    is_urgent: false,
    booked_by: 8,
    confirmed_by: 5,
    released_by: null,
    created_at: ts(10),
    confirmed_at: ts(4),
    released_at: null,
    procurement_notified: true,
    notes: 'FCL export — general cargo.',
    delivery_type: 'port-to-port',
    release_order_attached: true,
    release_order_fields: {
      reference_nbr: 'EBKG16474591',
      pickup_empty_date: future(2),
      validity_expiration_date: future(9),
      pickup_depot: 'SPECTRA INTEGRATED LOGISTICS PVT LTD',
      pickup_depot_address: 'No. 300 1/MU 125, Muthurajawela Industrial Zone, Wattala, Sri Lanka',
      cargo_description: 'General Cargo',
      cargo_weight: '16,000',
      cut_off_date: future(5),
      etd: future(7),
      eta: future(14),
      next_port_of_discharge: '',
      transport_mode: '',
      transport_carrier: '',
    } satisfies ReleaseOrderFields,
  },

  // ── CS › Pre-Advice (send-pre-advice) — door-to-door ────────────────────
  // Draft BL sent + SI submitted, pre-advice NOT yet sent. Door-to-door.
  {
    id: 'BKG-MOCK-013',
    quote_id: 'QT-MOCK-013',
    customer_name: 'CL Synergy Limited',
    origin: 'Montreal',
    destination: 'Colombo',
    shipping_line: 'MSC',
    vessel_name: 'MSC Asya',
    voyage_number: 'MA622R',
    container_type: "40'HC",
    quantity: 1,
    status: 'Released',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: 7,
    created_at: ts(20),
    confirmed_at: ts(14),
    released_at: ts(10),
    procurement_notified: true,
    notes: 'Door-to-door. Organic latex rubber sheets.',
    delivery_type: 'door-to-door',
    si_cutoff_date: future(3),
    bl_cutoff_date: future(3),
    vgm_cutoff_date: future(2),
    si_requested: true,
    si_submitted: true,
    draft_bl_sent: true,
    pre_advice_sent: false,
    master_bl_number: 'MEDUKL885309',
    master_bl_shipper: 'CL Synergy Limited',
    master_bl_consignee: 'Freight Masters Logistics Inc.',
    master_bl_recorded: true,
  },

  // ── CS › Pre-Advice (send-pre-advice) — port-to-door ──────────────────
  // Draft BL sent + SI submitted, pre-advice NOT yet sent. Port-to-door.
  {
    id: 'BKG-MOCK-014',
    quote_id: 'QT-MOCK-014',
    customer_name: 'Delmege Forsyth & Co.',
    origin: 'Colombo',
    destination: 'Toronto',
    shipping_line: 'Hapag-Lloyd',
    vessel_name: 'Berlin Express',
    voyage_number: 'BE-077W',
    container_type: "20'GP",
    quantity: 2,
    status: 'Released',
    is_urgent: true,
    booked_by: 8,
    confirmed_by: 5,
    released_by: 8,
    created_at: ts(18),
    confirmed_at: ts(12),
    released_at: ts(8),
    procurement_notified: true,
    notes: 'Port-to-door. Tea shipment — temperature sensitive.',
    delivery_type: 'port-to-door',
    si_cutoff_date: future(1),
    bl_cutoff_date: future(1),
    vgm_cutoff_date: future(0),
    si_requested: true,
    si_submitted: true,
    draft_bl_sent: true,
    pre_advice_sent: false,
  },

  // ── Admin › House BL (create-house-bl) — door-to-door ───────────────────
  // Master BL recorded, House BL not yet issued
  {
    id: 'BKG-MOCK-011',
    quote_id: 'QT-MOCK-011',
    customer_name: 'Softlogic Holdings',
    origin: 'Colombo',
    destination: 'Felixstowe',
    shipping_line: 'ONE',
    vessel_name: 'ONE Cosmos',
    voyage_number: 'OC-112W',
    container_type: "40'GP",
    quantity: 1,
    status: 'Released',
    is_urgent: false,
    booked_by: 7,
    confirmed_by: 5,
    released_by: 7,
    created_at: ts(28),
    confirmed_at: ts(18),
    released_at: ts(14),
    procurement_notified: true,
    notes: 'Door-to-door. Consignee: Softlogic UK Warehouse.',
    delivery_type: 'door-to-door',
    si_requested: true,
    si_submitted: true,
    master_bl_number: 'OOLU-123456789',
    master_bl_shipper: 'Softlogic Holdings (Pvt) Ltd',
    master_bl_consignee: 'Softlogic UK Warehouse Ltd',
    master_bl_recorded: true,
    house_bl_created: false,
  },
]

// ---------------------------------------------------------------------------
// Activity log — "cutoff recorded" entries for BKG-MOCK-006 onwards
// This prevents them from appearing in the Cutoff step (which only looks at
// this log), while they continue to appear in their own targeted steps.
// ---------------------------------------------------------------------------
const CUTOFF_DONE_IDS = [
  'BKG-MOCK-006', 'BKG-MOCK-007', 'BKG-MOCK-008',
  'BKG-MOCK-009', 'BKG-MOCK-010', 'BKG-MOCK-011',
  'BKG-MOCK-013', 'BKG-MOCK-014',
]

export const MOCK_ACTIVITY: ActivityEntry[] = CUTOFF_DONE_IDS.map(id => ({
  id: `ACT-MOCK-CUTOFF-${id}`,
  timestamp: ts(5),
  actor_role: 'CS' as const,
  actor_id: 7,
  action: `Recorded vessel cutoff schedule for ${MOCK_BOOKINGS.find(b => b.id === id)?.customer_name ?? id}.`,
  ref_type: 'booking' as const,
  ref_id: id,
  customer_name: MOCK_BOOKINGS.find(b => b.id === id)?.customer_name ?? '',
  pushed_to: 'CS' as const,
  notes: '',
}))
